[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_solquad_excercise = "3ke9swkGiippQAvFvHAmUGtvujEEA895HF7f6BFgL8pC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/eemcs/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
